---
version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
      include: "scope"
    allowed_updates:
      - match:
          dependency_type: "all"
          update_type: "all"
