language: java
jdk:
  - oraclejdk8
notifications:
  email: false

deploy:
  file_glob: true
  provider: releases
  api-key: ${GITHUB_API}
  file: ProtectMyFireplace.jar
  skip_cleanup: true
  on:
    tags: true